# Generated by Django 3.1.7 on 2021-03-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='fname',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='lname',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='pno',
            field=models.CharField(default='None', max_length=13),
        ),
        migrations.AddField(
            model_name='farmer',
            name='pwd',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='farmer',
            name='state',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='uname',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
