# Generated by Django 3.1.7 on 2021-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210317_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='None', max_length=100)),
                ('lname', models.CharField(default='None', max_length=100)),
                ('pno', models.CharField(default='None', max_length=13)),
                ('village', models.CharField(default='None', max_length=20)),
                ('district', models.CharField(default='None', max_length=20)),
                ('state', models.CharField(default='None', max_length=20)),
                ('uname', models.CharField(default='None', max_length=15)),
                ('pwd', models.CharField(default='None', max_length=30)),
                ('des', models.TextField()),
            ],
        ),
    ]
