# Generated by Django 3.1.7 on 2021-05-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='far_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.TextField()),
                ('far', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='vol_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.TextField()),
                ('vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('comsf', models.ManyToManyField(to='account.far_comment')),
                ('comsv', models.ManyToManyField(to='account.vol_comment')),
                ('far', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.farmer')),
            ],
        ),
    ]
